### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by Aur0raN** [Mekolaos/Aternos-On-Discord#1]
Hey, could you make a video on how to run this as I get multiple path errors when doing it myself.

**Comment by Mekolaos** [comment]
Could you describe the errors so I can fix them in the meantime ? I'll try to make a video asap.

**Comment by Mekolaos** [comment]
Hello. 

You have to create a .env file with the info on the discord bot you created for your server. I'll add a feature so it's easier and in the meantime will make a video on it, promise !

**Comment by Aur0raN** [comment]
No worries, I fixed the problem, there was a different popup in aternos in selenium that wasn't allowing it to click the proper element so I fixed it.

**Comment by Mekolaos** [comment]
Okay great !
I'll still fix up all of this mess and make it more user friendly. I'll update it as much as I can.
