### ISSUE TITLE
Coroutine was never awaited/<lambda>() type errror!?

### ISSUE THREAD

**Issue by 404CoderNotFound** [Mekolaos/Aternos-On-Discord#10]
Hi, so i managed to install all the requirements, but now when i run bot.py i get this: 
![image](https://user-images.githubusercontent.com/73307604/96961813-b9228880-1505-11eb-9ac4-7cec79ca720d.png)
I am running windows 10 with the latest version of python. Yes, i configured the bot token and stuff. Why does this happen and how do i fix it?

**Comment by 404CoderNotFound** [comment]
I fixed all issues, it works now! Yay!

**Comment by JendaPlayz** [comment]
Hi there im having the same issue.
How did you fix it?
