### ISSUE TITLE
Captcha issue

### ISSUE THREAD

**Issue by jericjan** [Mekolaos/Aternos-On-Discord#55]
I don't know if it's cause I'm using replit or what but, I tried running this with headless set to False and I would always get a captcha page when it visits the Aternos site. Maybe there's no way around this anymore? Just reporting my issue.

**Comment by TheBlobfish8** [comment]
I think that Aternos recognizes that you are connecting from a hosting service rather than a home network, so there's nothing to do but solve the captcha, or self host

**Comment by jericjan** [comment]
Gotcha. Tried hosting it on my actual PC and it worked. Thanks!

**Comment by pritam20ps05** [comment]
its due to webdriver detection use undetected chromedriver check my code https://github.com/pritam20ps05/mcscraper
it works pretty well and works 98% of the time my server personally uses it.
