### ISSUE TITLE
Gives error when attempting to run for the first time 

### ISSUE THREAD

**Issue by Burning290** [Mekolaos/Aternos-On-Discord#59]
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "Bot.py", line 10, in <module>
    from Configure import launch_config
  File "/home/caston/Aternos-On-Discord/Configure.py", line 1, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

I dont know how to fix please help

**Comment by Mekolaos** [comment]
Heya,
All you need to do is `pip install -r requirements.txt` in the root of the project's folder.
